# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95dd13839e9cbd15db1172fd7948a137f425ced5d7085c8700e028b3417b5712be665095eb3a073a1f7475fd09f9dce9c82b869d174ac47b0c72dcf5b22fbf70

test:
  secret_key_base: 429a631f4889ae2dc2ce1fe24d26ff1df2c6c574405d855b377074b8368e050933fbf854fcbd23ac8d6e1b040c6701240c81ad2931d8204179dfc501c5ebb99b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
